import { InterviewQuestion } from '@/types';

const GENERAL_QUESTIONS: InterviewQuestion[] = [
  { question: 'Tell me about yourself.', answer: 'Start with your current role, then briefly cover your background, key achievements, and why you are excited about this opportunity. Keep it to 2 minutes. Example: "I am currently a [role] with [X] years of experience specializing in [area]. I started my career at [company] where I [key achievement]. Most recently at [company], I [key achievement with metric]. I am now looking to bring my [skills] to a team where I can [goal aligned with the company]."', category: 'general' },
  { question: 'Why do you want to work for this company?', answer: 'Research the company mission, recent projects, and culture. Connect your skills and values to theirs. Example: "I have been following your work on [specific project/product] and I am impressed by [specific detail]. My experience in [relevant skill] aligns well with your team goals, and I am excited about the opportunity to contribute to [specific initiative]."', category: 'general' },
  { question: 'What are your greatest strengths?', answer: 'Pick 2-3 strengths relevant to the role and back each with a concrete example. Example: "One of my key strengths is [strength]. For example, at [company], I [specific example with result]. I also excel at [second strength], which I demonstrated when [specific example]."', category: 'general' },
  { question: 'What is your greatest weakness?', answer: 'Choose a real but non-critical weakness and show how you are improving it. Example: "I used to struggle with delegating tasks because I wanted everything done perfectly. I have since learned to trust my team by setting clear expectations and regular check-ins, which has actually improved our overall output quality."', category: 'general' },
  { question: 'Where do you see yourself in 5 years?', answer: 'Show ambition aligned with the company growth path. Example: "In 5 years, I see myself growing into a senior role where I can lead larger projects and mentor junior team members. I am particularly interested in [specific area the company works in] and want to deepen my expertise there while contributing to the team success."', category: 'general' },
  { question: 'Why are you leaving your current job?', answer: 'Stay positive and focus on growth, never badmouth your employer. Example: "I have had a great experience at my current company and learned a lot, but I am looking for a new challenge where I can [specific growth area] and work on [type of projects] that this role offers."', category: 'general' },
  { question: 'What motivates you?', answer: 'Connect your motivation to the role. Example: "I am motivated by solving complex problems and seeing the impact of my work. I particularly enjoy [specific aspect of the job] because it allows me to [what you find rewarding]."', category: 'general' },
  { question: 'How do you handle pressure and stress?', answer: 'Show a healthy coping strategy. Example: "I handle pressure by staying organized and breaking large tasks into smaller, manageable steps. I prioritize based on urgency and impact, and I am not afraid to ask for help or communicate with stakeholders when timelines are tight."', category: 'general' },
];

const BEHAVIORAL_QUESTIONS: InterviewQuestion[] = [
  { question: 'Tell me about a time you faced a difficult challenge at work. How did you handle it?', answer: 'Use the STAR method (Situation, Task, Action, Result). Example: "At [company], we faced [situation] when [what happened]. My task was to [your responsibility]. I took action by [specific steps you took]. As a result, [positive outcome with metric]."', category: 'behavioral' },
  { question: 'Describe a time you had a conflict with a coworker. How did you resolve it?', answer: 'Show emotional intelligence and problem-solving. Example: "A colleague and I disagreed on [topic]. I scheduled a one-on-one to understand their perspective. We found a compromise by [solution]. Our relationship improved and we successfully delivered [result]."', category: 'behavioral' },
  { question: 'Tell me about a time you failed. What did you learn?', answer: 'Show self-awareness and growth. Example: "I once [situation] which resulted in [failure]. I took responsibility and learned [lesson]. Since then, I [how you changed your approach] and have not had that issue again."', category: 'behavioral' },
  { question: 'Describe a time you showed leadership.', answer: 'Example: "When our team lead was unavailable, I stepped up to coordinate [project]. I organized daily stand-ups, assigned tasks based on strengths, and communicated with stakeholders. We delivered on time and the client was very satisfied."', category: 'behavioral' },
  { question: 'Tell me about a time you went above and beyond what was required.', answer: 'Example: "I noticed our deployment process was manual and error-prone. Even though it was not in my job description, I spent time automating it with scripts. This saved the team 5 hours per week and reduced errors by 80%. "', category: 'behavioral' },
];

const TECHNICAL_QUESTIONS: Record<string, InterviewQuestion[]> = {
  'software engineer': [
    { question: 'What is the difference between an array and a linked list?', answer: 'Arrays store elements in contiguous memory locations, allowing O(1) random access but O(n) insertion/deletion. Linked lists store elements in nodes with pointers, allowing O(1) insertion/deletion at known positions but O(n) random access. Arrays are better for indexing and searching; linked lists are better for frequent insertions and deletions.', category: 'technical' },
    { question: 'Explain the difference between SQL and NoSQL databases.', answer: 'SQL databases (MySQL, PostgreSQL) are relational, use structured schemas with tables, support ACID transactions, and are best for complex queries and relationships. NoSQL databases (MongoDB, Redis) are non-relational, have flexible schemas, are horizontally scalable, and are best for unstructured data, rapid development, and large-scale applications.', category: 'technical' },
    { question: 'What is REST and how does it differ from GraphQL?', answer: 'REST is an architectural style using HTTP methods (GET, POST, PUT, DELETE) on resource endpoints, returning fixed data structures. GraphQL is a query language where clients specify exactly what data they need in a single endpoint. REST is simpler and caches well; GraphQL prevents over/under-fetching and is more flexible.', category: 'technical' },
    { question: 'Explain the concept of Big O notation.', answer: 'Big O notation describes the upper bound of an algorithm time or space complexity as input size grows. Common complexities: O(1) constant, O(log n) logarithmic, O(n) linear, O(n log n) linearithmic, O(n^2) quadratic, O(2^n) exponential. It helps compare algorithm efficiency and identify bottlenecks.', category: 'technical' },
    { question: 'What is dependency injection and why is it useful?', answer: 'Dependency injection is a design pattern where dependencies are provided to a class instead of the class creating them. It promotes loose coupling, easier testing (mock dependencies), better reusability, and cleaner code. Common in frameworks like Spring (Java) and Angular (TypeScript).', category: 'technical' },
  ],
  'data analyst': [
    { question: 'What is the difference between INNER JOIN and LEFT JOIN in SQL?', answer: 'INNER JOIN returns only rows that have matching values in both tables. LEFT JOIN returns all rows from the left table plus matched rows from the right table; unmatched left rows get NULL for right columns. Use INNER JOIN when you only need matching records, LEFT JOIN when you need all left records regardless of matches.', category: 'technical' },
    { question: 'How would you handle missing or null values in a dataset?', answer: 'First, understand why data is missing (MCAR, MAR, MNAR). Options: (1) Drop rows/columns if missing data is small, (2) Impute with mean/median/mode for numerical, or mode for categorical, (3) Use predictive models like KNN or regression for imputation, (4) Create a "missing" category for categorical data. Document your approach and its assumptions.', category: 'technical' },
    { question: 'Explain the difference between correlation and causation.', answer: 'Correlation means two variables change together (statistical relationship), while causation means one variable directly causes the change in another. Correlation does not imply causation. To establish causation, you need controlled experiments, temporal precedence, and elimination of confounding variables.', category: 'technical' },
    { question: 'What SQL window functions have you used?', answer: 'Window functions perform calculations across related rows without collapsing them. Common ones: ROW_NUMBER() for ranking, RANK() and DENSE_RANK() for competitions, LAG() and LEAD() for comparing with previous/next rows, SUM/AVG with OVER() for running totals, NTILE() for bucketing. Example: "SELECT *, RANK() OVER(PARTITION BY dept ORDER BY salary DESC) FROM employees".', category: 'technical' },
  ],
  'product manager': [
    { question: 'How do you prioritize features for a product roadmap?', answer: 'I use frameworks like RICE (Reach, Impact, Confidence, Effort) or MoSCoW (Must, Should, Could, Won\'t). I consider customer value, business impact, development effort, and strategic alignment. I also factor in dependencies, risks, and feedback from stakeholders. The key is balancing quick wins with long-term strategic investments.', category: 'technical' },
    { question: 'How do you gather and incorporate user feedback?', answer: 'I use multiple channels: user interviews for deep qualitative insights, surveys for quantitative data, analytics for behavioral patterns, beta testing for early feedback, and support tickets for pain points. I synthesize findings into themes, validate with data, and prioritize based on frequency and impact. I close the loop by communicating changes back to users.', category: 'technical' },
    { question: 'How do you decide whether to build, buy, or partner?', answer: 'I evaluate: (1) Strategic value - is this core to our product? (2) Cost - build cost vs. buy cost over 3 years, (3) Time to market - can we build fast enough? (4) Quality - can we do it better than existing solutions? (5) Maintenance - ongoing cost of ownership. Build for competitive advantage, buy for speed and non-core, partner for mutual benefit.', category: 'technical' },
  ],
  'data scientist': [
    { question: 'Explain the bias-variance tradeoff.', answer: 'Bias is error from incorrect assumptions (underfitting), variance is error from sensitivity to training data fluctuations (overfitting). High bias = oversimplified model, high variance = overcomplex model. The tradeoff: decreasing bias increases variance and vice versa. The goal is to find the sweet spot that minimizes total error using regularization, cross-validation, and appropriate model complexity.', category: 'technical' },
    { question: 'What is cross-validation and why is it important?', answer: 'Cross-validation (k-fold) splits data into k subsets, trains on k-1 folds and validates on the remaining fold, repeating k times. It gives a more reliable estimate of model performance than a single train/test split, helps detect overfitting, and ensures the model generalizes. It is especially important with limited data.', category: 'technical' },
    { question: 'Explain the difference between supervised and unsupervised learning.', answer: 'Supervised learning uses labeled training data to learn a mapping from inputs to outputs (classification, regression). Examples: spam detection, price prediction. Unsupervised learning finds patterns in unlabeled data (clustering, dimensionality reduction). Examples: customer segmentation, anomaly detection. Semi-supervised combines both approaches.', category: 'technical' },
  ],
  'ui ux designer': [
    { question: 'Walk me through your design process.', answer: 'My process: (1) Discover - research users, competitors, and business goals, (2) Define - synthesize findings into user personas and problem statements, (3) Ideate - sketch and brainstorm solutions, (4) Design - create wireframes, then high-fidelity prototypes in Figma, (5) Test - usability testing with 5+ users, (6) Iterate - refine based on feedback, (7) Handoff - deliver specs and assets to developers with ongoing support.', category: 'technical' },
    { question: 'How do you handle accessibility in your designs?', answer: 'I follow WCAG guidelines: sufficient color contrast (4.5:1 for normal text), keyboard navigation support, screen reader compatibility with ARIA labels, focus indicators, alt text for images, and scalable text. I test with accessibility tools like axe and do manual testing with screen readers. I advocate for accessibility from the start, not as an afterthought.', category: 'technical' },
    { question: 'How do you respond to design feedback you disagree with?', answer: 'I listen first, ask clarifying questions to understand the reasoning, and evaluate it against user research and data. If the feedback conflicts with user needs, I present evidence diplomatically. If it is a preference, I propose A/B testing. I always focus on what is best for the user while respecting business constraints.', category: 'technical' },
  ],
  'marketing': [
    { question: 'How do you measure the success of a marketing campaign?', answer: 'I define KPIs based on campaign goals: brand awareness (impressions, reach, social mentions), engagement (CTR, shares, time on page), lead generation (form fills, email signups, MQLs), conversion (sales, signups, revenue), and ROI (CAC, LTV, ROAS). I use tools like Google Analytics, CRM dashboards, and attribution models to track performance across channels.', category: 'technical' },
    { question: 'How do you approach SEO for a new website?', answer: 'I start with keyword research to find high-value, achievable keywords. Then: (1) Technical SEO - site speed, mobile-friendly, XML sitemap, robots.txt, (2) On-page - title tags, meta descriptions, header structure, internal linking, (3) Content - high-quality, keyword-optimized, regularly updated, (4) Off-page - backlink building through outreach and content marketing. I monitor rankings, traffic, and conversions weekly.', category: 'technical' },
  ],
  'business analyst': [
    { question: 'How do you gather requirements from stakeholders?', answer: 'I use multiple techniques: (1) Interviews for detailed individual perspectives, (2) Workshops for group alignment, (3) Surveys for broad quantitative data, (4) Observation for current process understanding, (5) Document analysis for existing systems. I ask open-ended questions, listen actively, and validate findings with stakeholders. I document in user stories with acceptance criteria and get sign-off.', category: 'technical' },
    { question: 'How do you handle conflicting requirements from different stakeholders?', answer: 'I first understand each stakeholder\'s underlying need and business justification. I map requirements to business goals and identify conflicts. I facilitate a discussion to find common ground, present trade-offs with impact analysis, and escalate to the sponsor when needed. I document decisions and rationale for transparency.', category: 'technical' },
  ],
  'devops engineer': [
    { question: 'Explain the CI/CD pipeline and its benefits.', answer: 'CI/CD automates the build-test-deploy cycle. CI (Continuous Integration) merges code frequently, runs automated tests, and catches integration issues early. CD (Continuous Deployment/Delivery) automates release to staging/production. Benefits: faster releases, fewer bugs, consistent deployments, quick rollback, team productivity. Tools: Jenkins, GitLab CI, GitHub Actions, ArgoCD.', category: 'technical' },
    { question: 'What is Infrastructure as Code and why is it important?', answer: 'IaC manages infrastructure through code (Terraform, CloudFormation, Ansible) instead of manual configuration. Benefits: (1) Version control for infrastructure, (2) Reproducible environments, (3) Consistency across dev/staging/prod, (4) Automated scaling and disaster recovery, (5) Documentation through code. It reduces human error and enables DevOps practices.', category: 'technical' },
  ],
};

export function getInterviewQuestions(jobRole: string): InterviewQuestion[] {
  const normalized = jobRole.toLowerCase().trim();
  let technicalQuestions: InterviewQuestion[] = [];

  for (const [key, questions] of Object.entries(TECHNICAL_QUESTIONS)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      technicalQuestions = questions;
      break;
    }
  }

  const selected = [
    ...GENERAL_QUESTIONS.slice(0, 3),
    ...BEHAVIORAL_QUESTIONS.slice(0, 3),
    ...technicalQuestions.slice(0, 4),
  ];

  return selected;
}
